name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pillow

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --windowed ^
            --name "ReferenceChecker" ^
            --icon "assets/panther_icon.ico" ^
            --add-data "assets;assets" ^
            --add-data "docs;docs" ^
            reference_checker.py
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReferenceChecker-Windows
          path: dist/ReferenceChecker.exe

      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/ReferenceChecker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
